CREATE TABLE IF NOT EXISTS booking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_id VARCHAR(100),
  name VARCHAR(255),
  bike VARCHAR(255),
  duration INT,
  price INT,
  deposit INT,
  status VARCHAR(50),
  start_date DATE,
  end_date DATE,
  pickup_type VARCHAR(50),
  delivery_address TEXT,
  promo_code VARCHAR(100),
  promo_discount_amount INT,
  promo_applied BOOLEAN DEFAULT false,
  currency_unit VARCHAR(10),
  applied_exchange_rate NUMERIC,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE booking ADD COLUMN IF NOT EXISTS batch_sent_at TIMESTAMP;
ALTER TABLE booking ADD COLUMN IF NOT EXISTS batch_attempts INT DEFAULT 0;

CREATE TABLE IF NOT EXISTS audit_email (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_name VARCHAR(200) NOT NULL,
  reference_id VARCHAR(100),
  payload TEXT,
  subject TEXT,
  message_id VARCHAR(200),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO booking (wa_id, name, bike, duration, price, status, start_date, end_date)
VALUES ('+1234567890', 'Alice Example', 'Mountain-1', 3, 150, 'CONFIRMED', '2025-11-24', '2025-11-27');
